openapi: 3.0.3
info:
  title: 'SC: Risk Visualisation V1 API'
  version: 1.0.0
  description: >-
    API providing the capability to retrieve the Risk Relationships for an organization in Atradius.


    ### Apiary Document Version Details


    |Version Number |Version Description |

    |:---------|:---------|

    |0.1|Service design for 16 services in v2 with API header change|


    ### Request Headers


    |Header |Sample Value |Mandatory |Description | 

    |:---------|:---------|:-------|:-------|

    |Content-Type|application/json|Yes|Media type of the resource.|

    |Authorization |"Bearer 527TIUuRrkpjwepX24ZSng.."<br>
    YWxhZGRpbjpvcGVuc2VzYW1l...<br> NMExhZGRpbjtyuGVuc2UzYx4.. |Yes |OAuth 2
    Authorization.| 

    |Atradius-Origin-User-Id |pt.John01 |Yes |Name of the user who is performing
    an action in a system (Note this is normally the login ID coming from the
    LDAP.|

    |Atradius-Origin-Application |BBT |Yes |Identification of the application
    which invoked the service.|

    |Atradius-Origin-Service |AnalysisDecisions |Yes |The name of origin
    (parent) service which is invoked.| 

    |Atradius-Invocation-Service |http://atradius.com/bbt/OrganisationSearch
    |Yes |The invocation service URL.| 

    |Atradius-Message-Timestamp |Thu, 15 Nov 2018 08:12:31 CET |Yes  |The
    timestamp when the client is invoked the origin service.| 

    |Atradius-Message-Id|efeeehfn73849grre|Yes|Unique identifier of the message
    that has been send.|

    |Atradius-Correlation-Id |5c4c8sda |Yes  |Unique identifier of a transaction
    over various applications / components.| 

    |Atradius-Concurrency-Control-Version|1|No| A placeholder were we can store
    a string with relevant information to perform in the data store the
    verification of the optimistic concurrency control. Block to capture the
    information which might be required as part of the Optimistic concurrency
    control (OCC) which is a concurrency control method applied to transactional
    systems.|


    ### Response Headers


    |Header |Sample Value |Mandatory
    |Description                                       | 

    |:---------|:---------|:-------|:-------|

    |resultcode |2XX/4XX/5XX |No |A response that can be returned to an
    application, <br> even to indicate that the request was successful.| 

    |description |Results retrieved successfully |No |A description that
    corresponds with the response code, even to indicate that the request was
    successful. | 

    |responseTimeStamp |Thu, 15 Nov 2018 08:12:33 CET |No |The timestamp when
    the client receives the response.|


    ### GET services with effective dates


    |FROM DATE |TO DATE |API Orchestration Description  |

    |:---------|:---------|:-------|:-------|

    |Null      |Null   | All the records irrespective of the dates are fetched.|

    |Date   |Null   |All the records where the <b>FROM DATE</b> from the input
    falls between the <i>effective from</i> and <i>effective to</i> dates in the
    table are fetched.|

    |Null   |Date   |Not Supported|

    |Date   |Date   |All the records where the <b>FROM DATE</b> and the <b>TO
    DATE</b> from the input falls between the <i>effective from</i> and
    <i>effective to</i> dates in the table are fetched.|
servers:
  - url: https://localhost:8080
paths:
  /v1/sc/org-data/risk-data-api:
      $ref: "./paths/riskRelationships.yaml"



